### ISSUE TITLE
Comparison null string to zero (int)

### ISSUE THREAD

**Issue by lnkgyv** [kusalananda/shell-toolbox#2]
I've just pulled `devel` branch, also reconfigure & make. Start it:
```
[yurij@centos7 src]$ ./shell
./shell: line 142: [: : integer expression expected
Starting /bin/bash in /tmp/shell-bash.BuwfbqXK
$ exit
exit
Removing /tmp/shell-bash.BuwfbqXK
``` 

Assume that `keep` variable need to set to zero before handle cmdline options.

**Comment by kusalananda** [comment]
Good catch! I'm running under OpenBSD's `/bin/sh`, which is `ksh`, so that must be a difference in how empty variables are evaluated in arithmetic contexts.

Will fix immediately.

**Comment by kusalananda** [comment]
Well, I don't know if it had anything to do with arithmetic context or not, but `ksh` happily evaluates `[ "" -eq 1 ]` as false anyway, while `bash` throws a fit.

Much thanks!

**Comment by lnkgyv** [comment]
It's `bash` behaviour:
```
[yurij@centos7 src]$ [ "" -eq 3 ]
-bash: [: : integer expression expected
[yurij@centos7 src]$ [ 3 -eq 3 ]
[yurij@centos7 src]$ var=3
[yurij@centos7 src]$ [ "$var" -eq 3 ]
[yurij@centos7 src]$ var=
[yurij@centos7 src]$ [ "$var" -eq 3 ]
-bash: [: : integer expression expected
[yurij@centos7 src]$ var=a
[yurij@centos7 src]$ [ "$var" -eq 3 ]
-bash: [: a: integer expression expected
```
